-- 003 · Secciones del catálogo (punto de secciones)
--
-- El catálogo gana navegación por secciones (`seccion`), y cada producto pasa a
-- pertenecer a una (`producto.seccion_id`). Los productos que ya existen se
-- cobijan en la sección `dulces` de su negocio, igual que hace el código en cada
-- arranque (`CatalogoService.asignarSeccionDulces()`): "dulces" es la sección
-- especial del catálogo heredado y ADC la esconde en sus respuestas.
--
-- Idempotente y a prueba de orden: con `IF NOT EXISTS` da igual si esto corre
-- antes o después de desplegar el código nuevo (si el código ya se desplegó,
-- `synchronize` habrá creado la tabla y la columna, y aquí solo se rellena el
-- backfill). No borra nada.
--
-- ────────────────────────────────────────────────────────────────────────────
-- 1 · La tabla `seccion`, con el UNIQUE(negocio, nombre) que pide la entidad.
--
-- `id serial` a propósito: es lo que genera `synchronize` en el código nuevo
-- (`@PrimaryGeneratedColumn('increment')`, Postgres lo materializa con un
-- `nextval` de secuencia y no con `GENERATED BY DEFAULT AS IDENTITY`). Si se
-- escribiera con identity, al desplegar después el código, `synchronize` vería
-- la columna "distinta" y querría rehacerla. Con `serial` no hay fricción.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seccion (
  id serial PRIMARY KEY,
  nombre varchar(60) NOT NULL,
  negocio varchar(16) NOT NULL DEFAULT 'delys',
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_seccion_negocio_nombre UNIQUE (negocio, nombre)
);

-- ────────────────────────────────────────────────────────────────────────────
-- 2 · `producto.seccion_id`, la FK hacia la tabla nueva.
--
-- La columna llega `integer` y `NULL` (los productos viejos no tenían sección);
-- la asignación real la hace el backfill del paso 3. La FK solo se añade si
-- `producto` no tiene ninguna: si el código se desplegó antes, `synchronize`
-- ya creó la suya con un nombre al azar, y añadir esta daría FKs duplicadas.
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE producto
  ADD COLUMN IF NOT EXISTS seccion_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'producto'::regclass
       AND contype = 'f'
  ) THEN
    ALTER TABLE producto
      ADD CONSTRAINT fk_producto_seccion
      FOREIGN KEY (seccion_id) REFERENCES seccion (id);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────────────────
-- 3 · Backfill: los productos sin sección pasan a la sección `dulces` de su
--     negocio (creándola si no existe). Idempotente: la segunda vez no hay
--     filas con `seccion_id IS NULL` que mover.
-- ────────────────────────────────────────────────────────────────────────────
INSERT INTO seccion (nombre, negocio)
SELECT 'dulces', negocio
  FROM (SELECT DISTINCT negocio FROM producto WHERE seccion_id IS NULL) s
ON CONFLICT (negocio, nombre) DO NOTHING;

UPDATE producto p
SET seccion_id = sec.id
FROM seccion sec
WHERE p.seccion_id IS NULL
  AND sec.nombre = 'dulces'
  AND sec.negocio = p.negocio;

-- ────────────────────────────────────────────────────────────────────────────
-- Comprobaciones esperadas:
--   \d foto seccion                       -- tabla con UNIQUE(negocio, nombre)
--   SELECT id, nombre, negocio FROM seccion;   -- una fila 'dulces' por negocio
--   SELECT p.id, p.nombre, s.nombre AS seccion
--     FROM producto p LEFT JOIN seccion s ON s.id = p.seccion_id;
--     → todo con su sección 'dulces'; el código mueve los que haya que mover.
--
-- Datos: ninguna fila se borra ni se modifica más allá del `seccion_id` que
-- venían a null, que cobija la sección heredada.
-- ────────────────────────────────────────────────────────────────────────────